name: security_control_app
description: Remote Security Control Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  vibration: ^3.1.3
  device_info_plus: ^9.1.2
  connectivity_plus: ^7.0.0
  # Firebase dependencies removed - using REST API instead
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
